# THESIS FOR MASTERS DEGREE IN MICRO DATA ANALYSIS

# Creating Financial Database for Education and Research: Using WEB SCRAPING Technique

Importing libraries

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed.
  
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt

import plotly.express as px
import plotly.graph_objects as go

from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)

Importing GRI text data files:

In [3]:
data_2017 = pd.read_csv('C:/Users/admin/Desktop/Thesis/2017.csv')

In [4]:

data_2017.columns

Index(['Featured Report?', 'Name', 'GOLD Community', 'Size',
       'Organization type', 'Listed/Non-listed', 'Sector', 'Country',
       'Country Status', 'Region', 'Date Added', 'Title', 'Publication Year',
       'Integrated', 'Type', 'Adherence Level', 'Status', 'GRI Service',
       'External Assurance', 'Type of Assurance Provider',
       'Assurance Provider', 'Stakeholder Panel/ Expert Opinion',
       'Assurance Scope', 'Level of Assurance',
       'Assurance Standard: AA1000 AS', 'Assurance Stanadard: ISAE3000',
       'Assurance Standard: national (general)',
       'Assurance Standard: national (sustainability)',
       'Sector Supplements (Final)', 'OECD', 'UNGC', 'CDP', 'IFC', 'ISO',
       'SDGs', 'GRI Content Index URL', 'Report Pdf Address',
       'Report Html Address', 'Report Drt Address', 'Database link'],
      dtype='object')

In [5]:
print(data_2017.shape)

data_2017.head()

(7227, 40)

,Featured Report?,Name,GOLD Community,Size,Organization type,Listed/Non-listed,Sector,Country,Country Status,Region,...,UNGC,CDP,IFC,ISO,SDGs,GRI Content Index URL,Report Pdf Address,Report Html Address,Report Drt Address,Database link
0,No,Alembic Pharmaceuticals Limited,No,MNE,Private company,Listed,Healthcare Products,India,DAC-LMICT,Asia,...,No,No,No,No,No,NaN,http://www.alembicpharmaceuticals.com/wp-conte...,http://www.alembicpharmaceuticals.com/annual-r...,NaN,http://database.globalreporting.org/reports/ed...
1,No,Anhui Water Resources Development Company,No,Large,State-owned company,Listed,Water Utilities,Mainland China,DAC-UMICT,Asia,...,NaN,NaN,NaN,NaN,NaN,NaN,http://static.sse.com.cn/disclosure/listedinfo...,NaN,NaN,http://database.globalreporting.org/reports/55...
2,No,"Baosteel Co., Ltd.",No,Large,Subsidiary,Listed,Construction Materials,Mainland China,DAC-UMICT,Asia,...,No,No,No,No,No,NaN,http://tv.baosteel.com/web/plc/pdf/SR2016.pdf,NaN,NaN,http://database.globalreporting.org/reports/74...
3,No,Baowu Steel,No,Large,State-owned company,Non-listed,Metals Products,Mainland China,DAC-UMICT,Asia,...,No,No,No,No,No,,http://tv.baosteel.com/web/plc/csr/2016csr.pdf,NaN,NaN,http://database.globalreporting.org/reports/93...
4,No,CRRC,No,Large,State-owned company,Listed,Railroad,Mainland China,DAC-UMICT,Asia,...,NaN,NaN,NaN,NaN,NaN,NaN,http://pdf.dfcfw.com/pdf/H2_AN2017032904484139...,NaN,NaN,http://database.globalreporting.org/reports/18...

In [5]:
df_2017_filtered = data_2017[(data_2017['Sector'] == 'Telecommunications') & (data_2017['Listed/Non-listed'] == 'Listed')]
df_2017_filtered.head()

,Featured Report?,Name,GOLD Community,Size,Organization type,Listed/Non-listed,Sector,Country,Country Status,Region,...,UNGC,CDP,IFC,ISO,SDGs,GRI Content Index URL,Report Pdf Address,Report Html Address,Report Drt Address,Database link
41,No,A1,No,Large,Private company,Listed,Telecommunications,Austria,OECD,Europe,...,NaN,NaN,NaN,NaN,NaN,NaN,http://cdn12.a1.net/m/resources/media/pdf/A1-U...,NaN,NaN,http://database.globalreporting.org/reports/32...
116,No,Adapt IT Group,No,Large,Private company,Listed,Telecommunications,South Africa,DAC-UMICT,Africa,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.adaptit.co.za/Documents/Adapt%20IT...,https://www.adaptit.co.za/Documents/Adapt%20IT...,NaN,http://database.globalreporting.org/reports/eb...
139,No,Advanced Info Service,No,Large,Private company,Listed,Telecommunications,Thailand,DAC-UMICT,Asia,...,Yes,No,No,No,Yes,NaN,http://advanc.listedcompany.com/misc/sustainab...,http://investor.ais.co.th/sustainability_repor...,NaN,http://database.globalreporting.org/reports/c0...
290,No,Algar Telecom (Former CTBC),No,Large,Private company,Listed,Telecommunications,Brazil,DAC-UMICT,Latin America & the Caribbean,...,Yes,No,No,No,No,NaN,NaN,http://www.globalri.com.br/algar/2016/telecom/pt/,NaN,http://database.globalreporting.org/reports/2e...
346,No,Altron (Allied Electronics Corporation Limited),No,MNE,Private company,Listed,Telecommunications,South Africa,DAC-UMICT,Africa,...,Yes,Yes,No,No,No,http://www.altron.com/iar2017/static/pdfs/2017...,http://www.altron.com/iar2017/static/pdfs/2017...,http://www.altron.com/iar2017/,NaN,http://database.globalreporting.org/reports/73...

In [6]:
print(df_2017_filtered.shape)

(162, 40)

In [7]:

df_2017_filtered = df_2017_filtered.query ('Country in ["Australia", "Japan", "Germany", "Canada", "Russian Federation", "Brazil", "France", "Spain", "India", "Italy","Mainland China", "United Kingdom of Great Britain and Northern Ireland", "United States Of America"]')                                    
df_2017_filtered_2 = df_2017_filtered.rename(columns = {'Publication Year': 'Year'}, inplace = False)
df_2017_filtered_3 = df_2017_filtered_2[df_2017_filtered_2.Year == 2017]
df_2017_filtered_3.head()

,Featured Report?,Name,GOLD Community,Size,Organization type,Listed/Non-listed,Sector,Country,Country Status,Region,...,UNGC,CDP,IFC,ISO,SDGs,GRI Content Index URL,Report Pdf Address,Report Html Address,Report Drt Address,Database link
290,No,Algar Telecom (Former CTBC),No,Large,Private company,Listed,Telecommunications,Brazil,DAC-UMICT,Latin America & the Caribbean,...,Yes,No,No,No,No,NaN,NaN,http://www.globalri.com.br/algar/2016/telecom/pt/,NaN,http://database.globalreporting.org/reports/2e...
423,No,Anhui WantongÂ Technology,No,Large,Private company,Listed,Telecommunications,Mainland China,DAC-UMICT,Asia,...,No,No,No,No,No,NaN,http://pdf.dfcfw.com/pdf/H2_AN2017022703678673...,NaN,NaN,http://database.globalreporting.org/reports/f9...
891,No,Beijing Dynamic Power,No,Large,Private company,Listed,Telecommunications,Mainland China,DAC-UMICT,Asia,...,NaN,NaN,NaN,NaN,NaN,NaN,http://pdf.dfcfw.com/pdf/H2_AN2017041905144610...,NaN,NaN,http://database.globalreporting.org/reports/61...
896,No,Beijing Gehua CATV,No,Large,Private company,Listed,Telecommunications,Mainland China,DAC-UMICT,Asia,...,NaN,NaN,NaN,NaN,NaN,NaN,http://pdf.dfcfw.com/pdf/H2_AN2017033104570934...,NaN,NaN,http://database.globalreporting.org/reports/69...
923,No,Bell Canada,No,Large,Private company,Listed,Telecommunications,Canada,OECD,Northern America,...,Yes,No,No,No,No,http://www.bce.ca/responsibility/corporate-res...,NaN,http://www.bce.ca/responsibility/corporateresp...,NaN,http://database.globalreporting.org/reports/bb...

In [8]:
writer = pd.ExcelWriter('uk.xlsx', engine='xlsxwriter')
df_2017_filtered_3.to_excel(writer, index = True)
writer.save()

# Web Scrapiing with yahoo finance

company-name-to-ticker-yahoo-finance

In [9]:

# Yahoo  finance doesn't allow for the searching of information using names, only tickers.
# The purpose of this algorithm is to convert any company entered into a ticker.

# Program extracting all columns 
# name in Python 
import xlrd 
import google
from googlesearch import search
from yahoo_finance import *
import yfinance as yf
import pandas as pd    

loc = r"C:/Users/admin/uk.xlsx"
  
wb = xlrd.open_workbook(loc)  
sheet = wb.sheet_by_index(0) 

# For row 0 and column 0 
final = []
lists = []
sheet.cell_value(0, 0) 

for i in range(sheet.nrows):
    lists1 = []
    link = []
    
    names =sheet.cell_value(i, 0)
    lists.append(names)
    searchval = 'yahoo finance '+names
    
    #limits to the first link
    for url in search(searchval, stop=1):
        link.append(url)

    link = str(link[0])
    link=link.split("/")
    if link[-1]=='':
        ticker=link[-2]
        lists1.append(ticker)
        
    else:
        x=link[-1].split('=')
        ticker=x[-1]
    final.append(lists1)
    lists1 = []
    
df = pd.DataFrame(lists)
df1 = pd.DataFrame(final)

df.insert(1,'symbols',df1)


Saipem SpA (SPM.MI)

https://finance.yahoo.com/quote/SPM.MI/financials?p=SPM.MI

In [10]:
df_reset = df.drop(df.index[[0]])
df_final =df_reset.dropna()
df_finals = df_final.rename(columns = { 0: 'Names of companies', 'symbols': 'ticker symbols'}, inplace = False)
df_finals.reset_index(drop=True, inplace=True)
df_list = df_finals['ticker symbols'].tolist()
print(df_finals)
df_list1 = df_finals['Names of companies'].tolist()
#df_list1

                                  Names of companies       ticker symbols
0                           Anhui WantongÂ Technology            002331.sz
1                              Beijing Dynamic Power            600405.ss
2                                Beijing Gehua CATV             600037.ss
3                                        Bell Canada               BCE.TO
4                                      Bharti Airtel              history
5                                           BT Group               BT-A.L
6                                    Changyuan Group            600525.ss
7                                       China Mobile                  CHL
8                                      China Telecom                  CHA
9                                       China Unicom                  CHU
10         China United Network Communications Group            600050.SS
11                  CITIC GuoanÂ InformationÂ Industry            000839.SZ
12                                  Daheng New Epoch            600288.ss
13                       Datang Telecom Technology              600198.SS
14                                  Deutsche Telekom               DTE.DE
15  Fiberhome Telecommunication Technologies Company            600498.SS
16                                               GCI                  GCI
17                                   GRUPO EUSKALTEL               EKT.MC
18                                           Invengo            002161.sz
19                                        Kddi Corp.                KDDIY
20                                           MegaFon                mfoyy
21                                               MTS                 MTSC
22                                               NTT                NTT.F
23                                        NTT DoCoMo               9437.T
24                                                Oi                   OI
25                    Orange (former France Telecom)               ORA.PA
26                                           Ourpalm            300315.sz
27           Radiante Engenharia de TelecomunicaÃ§Ãµes  www.radiante.com.br
28                          Reliance Communications               rcom.ns
29                             Rogers Communications             RCI-B.TO
30                                        Rostelecom              RTKM.ME
31                        ShanghaiÂ BaosightÂ Software            600845.SS
32                       Suzhou New District Hi-Tech            600736.SS
33                                    TaijiÂ Computer            002368.SZ
34                               Tata Communications          TATACOMM.NS
35                                        Telefonica                  TEF
36                                 Telefonica Brasil                  VIV
37                    TelefÃ³nica Deutschland Holding               O2D.DE
38                                           Telstra               tls.ax
39                                             Telus                 t.to
40                           TianmaÂ Microelectronics            000050.SZ
41                                 TIM ParticipaÃ§Ãµes                 news
42                                              Vivo                 VIVO
43                                   Vodafone Espana                  VOD
44                                    Vodafone Group                  VOD
45  Wangsu Science & Technology (ChinaNetCenter Co.)            300017.SZ
46                                            YGSOFT            002063.sz

In [11]:
writer = pd.ExcelWriter('uk_1.xlsx', engine='xlsxwriter')
df_finals.to_excel(writer, index = True)
writer.save()

Scraping Income Statement data from Yahoo Finance

In [1]:
from lxml import html
from lxml import html
import requests
import yfinance as yf
import numpy as np
import pandas as pd

def scrape_table(url):
    page = requests.get(url)
    tree = html.fromstring(page.content)
    table = tree.xpath("//h1/text()")
    print(table)
    table_rows = tree.xpath("//div[contains(@class, 'D(tbr)')]")
    
# Ensure that some table rows are found; if none are found, then it's possible
# that Yahoo Finance has changed their page layout, or have detected
# that you're scraping the page.
    try:
        assert len(table_rows) > 0

    except AssertionError as msg:
        print(msg)
    
    parsed_rows = []
    
    for table_row in table_rows:
        parsed_row = []
        el = table_row.xpath("./div")
    
        none_count = 0
    
        for rs in el:
            try:
                (text,) = rs.xpath('.//span/text()[1]')
                parsed_row.append(text)
            except ValueError:
                parsed_row.append(np.NaN)
                none_count += 1

        if (none_count < 4):
            parsed_rows.append(parsed_row)
    
    df = pd.DataFrame(parsed_rows)
    df = df.set_index(0)
    df = df.dropna()
    df = df.transpose()
    df = df.replace('-', '0')
    indexNames = df[(df['Breakdown'] == 'ttm')].index
    df.drop(indexNames , inplace=True)
    df = df.fillna(0)
    
    numeric_columns = list(df.columns)[1::] 

    for column_name in numeric_columns:
        df[column_name] = df[column_name].str.replace(',', '') # Remove the thousands separator
        df[column_name] = df[column_name].astype(np.float64) # Convert the column to float64

    return df

In [2]:
#symbols = ['AAPL', 'MFT.NZ']
financials = {}
lss = []
#create a dictionary of ticker names and their respective statements' urls

import xlrd 
import google
import pandas as pd    
loc = r"C:\Users\admin\uk_1.xlsx"
  
wb = xlrd.open_workbook(loc) 
sheet = wb.sheet_by_index(0) 

for i in range(sheet.nrows):
    company = sheet.cell_value(i, 0)
    symbols =sheet.cell_value(i, 1)
    #for symbol in symbols:
    financials[symbols] = ['https://finance.yahoo.com/quote/' + symbols + '/financials?p=' + symbols]
    lss.append(company)

data = pd.DataFrame()

for f, ls in zip(financials, lss):
    try:
        countries = yf.Ticker(f).info['country']
        names = yf.Ticker(f).info['shortName']
    except IndexError:
        countries = 'null'
        names = 'null'
    except ValueError:
        countries = 'null'
        names = 'null'
    except KeyError as ke:
        print('Key Not Found in Dictionary:', ke)
        continue
    except AssertionError:
        print('Assertion error')
    df_income_statement = scrape_table(financials[f][0])
    df_income_statement.insert(1, 'Symbol', f)   
    df_income_statement.insert(2, 'Country', countries)
    df_income_statement.insert(3, 'name of companies', ls)
    data = data.append(df_income_statement)

['Anhui Wantong Technology Co.,Ltd. (002331.SZ)']
['Beijing Dynamic Power Co., Ltd. (600405.SS)']
['Beijing Gehua CATV Network Co., LTD. (600037.SS)']
['BCE Inc. (BCE.TO)']
['BT Group plc (BT-A.L)']
['Changyuan Technology Group Ltd. (600525.SS)']
['China Mobile Limited (CHL)']
['China Telecom Corporation Limited (CHA)']
['China Unicom (Hong Kong) Limited (CHU)']
['China United Network Communications Limited (600050.SS)']
['CITIC Guoan Information Industry Co., Ltd. (000839.SZ)']
['Daheng New Epoch Technology Inc. (600288.SS)']
['Datang Telecom Technology Co., Ltd. (600198.SS)']
['Deutsche Telekom AG (DTE.DE)']
['Fiberhome Telecommunication Technologies Co., Ltd. (600498.SS)']
['Gannett Co., Inc. (GCI)']
['Euskaltel, S.A. (EKT.MC)']
['Invengo Information Technology Co., Ltd (002161.SZ)']
['KDDI Corporation (KDDIY)']
['MTS Systems Corporation (MTSC)']
['Nippon Telegraph and Telephone Corporation (NTT.F)']
['Orange S.A. (ORA.PA)']
['Ourpalm Co., Ltd. (300315.SZ)']
['Reliance Communications Limited (RCOM.NS)']
['Public Joint Stock Company Rostelecom (RTKM.ME)']
['Shanghai Baosight Software Co.,Ltd. (600845.SS)']
['Suzhou New District Hi-Tech Industrial Co.,Ltd (600736.SS)']
['Taiji Computer Corporation Limited (002368.SZ)']
['Tata Communications Limited (TATACOMM.NS)']
['TelefÃ³nica, S.A. (TEF)']
['TelefÃ´nica Brasil S.A. (VIV)']
['TelefÃ³nica Deutschland Holding AG (O2D.DE)']
['Telstra Corporation Limited (TLS.AX)']
['TELUS Corporation (T.TO)']
['Tianma Microelectronics Co., Ltd. (000050.SZ)']
['Meridian Bioscience, Inc. (VIVO)']
['Vodafone Group Plc (VOD)']
['Wangsu Science & Technology Co.,Ltd. (300017.SZ)']
['YGSOFT Inc. (002063.SZ)']

In [4]:
data.head(20)

,Breakdown,Symbol,Country,name of companies,Total Revenue,Cost of Revenue,Gross Profit,Operating Expense,Operating Income,Net Non Operating Interest Income Expense,...,Total Unusual Items Excluding Goodwill,Total Unusual Items,Normalized EBITDA,Tax Rate for Calcs,Tax Effect of Unusual Items,Other Income Expense,Diluted NI Available to Com Stockholders,Reconciled Depreciation,Rent Expense Supplemental,Average Dilution Earnings
2,12/31/2019,002331.sz,null,Anhui WantongÂ Technology,1459618.0,995655.0,463963.0,253819.0,210145.0,3122.0,...,-12996.0,-12996.0,264397.0,0.0,-1.949000e+03,NaN,NaN,NaN,NaN,NaN
3,12/31/2018,002331.sz,null,Anhui WantongÂ Technology,1249370.0,878390.0,370980.0,199970.0,171010.0,1924.0,...,-51377.0,-51377.0,212607.0,0.0,-9.207000e+03,NaN,NaN,NaN,NaN,NaN
4,12/31/2017,002331.sz,null,Anhui WantongÂ Technology,995817.0,750046.0,245771.0,131148.0,114623.0,2277.0,...,-10253.0,-10253.0,145464.0,0.0,-1.674000e+03,NaN,NaN,NaN,NaN,NaN
2,12/31/2019,600405.ss,null,Beijing Dynamic Power,1244740.0,840621.0,404119.0,322535.0,36256.0,-49415.0,...,-22294.0,-22294.0,213687.0,0.0,-7.101000e+03,NaN,NaN,NaN,NaN,NaN
3,12/31/2018,600405.ss,null,Beijing Dynamic Power,909557.0,629245.0,280312.0,364080.0,-126886.0,-54220.0,...,-78511.0,-78511.0,-24442.0,0.0,-1.962800e+04,NaN,NaN,NaN,NaN,NaN
4,12/31/2017,600405.ss,null,Beijing Dynamic Power,1221878.0,831082.0,390796.0,314348.0,32888.0,-33242.0,...,-26420.0,-26420.0,181012.0,0.0,-1.418000e+03,NaN,NaN,NaN,NaN,NaN
2,12/31/2019,600037.ss,China,Beijing Gehua CATV,2758605.0,2157321.0,601284.0,326355.0,424944.0,149877.0,...,-48466.0,-48466.0,1236573.0,0.0,-9.983119e+02,NaN,NaN,NaN,NaN,NaN
3,12/31/2018,600037.ss,China,Beijing Gehua CATV,2725247.0,2010497.0,714750.0,300561.0,588283.0,174015.0,...,-34592.0,-34592.0,1320882.0,0.0,-3.642763e+02,NaN,NaN,NaN,NaN,NaN
4,12/31/2017,600037.ss,China,Beijing Gehua CATV,2698183.0,1956098.0,742084.0,262806.0,597575.0,118822.0,...,-47168.0,-47168.0,1423416.0,0.0,-3.380108e+02,NaN,NaN,NaN,NaN,NaN
2,12/31/2019,BCE.TO,Canada,Bell Canada,23964000.0,11903000.0,12061000.0,6215000.0,5846000.0,-1195000.0,...,-230000.0,-230000.0,10209000.0,0.0,-5.934000e+04,-265000.0,3040000.0,4398000.0,NaN,NaN
3,12/31/2018,BCE.TO,Canada,Bell Canada,23468000.0,11850000.0,11618000.0,6177000.0,5441000.0,-1069000.0,...,-379000.0,-379000.0,9430000.0,0.0,-9.512900e+04,-404000.0,2785000.0,4014000.0,NaN,NaN
4,12/31/2017,BCE.TO,Canada,Bell Canada,22719000.0,11469000.0,11250000.0,5922000.0,5328000.0,-1027000.0,...,-256000.0,-256000.0,9142000.0,0.0,-6.630400e+04,-292000.0,2786000.0,3850000.0,NaN,NaN
2,3/31/2020,BT-A.L,United Kingdom,BT Group,22905000.0,9647000.0,13258000.0,9561000.0,3697000.0,-854000.0,...,-457000.0,-457000.0,8004000.0,0.0,-1.201910e+05,NaN,1734000.0,4274000.0,0.0,NaN
3,3/31/2019,BT-A.L,United Kingdom,BT Group,23428000.0,10053000.0,13375000.0,9560000.0,3815000.0,-714000.0,...,-436000.0,-436000.0,7396000.0,0.0,-8.284000e+04,NaN,2159000.0,3546000.0,801000.0,NaN
4,3/31/2018,BT-A.L,United Kingdom,BT Group,23723000.0,5514000.0,18209000.0,14241000.0,3968000.0,-729000.0,...,-622000.0,-622000.0,7493000.0,0.0,-1.212900e+05,NaN,2032000.0,3514000.0,732000.0,NaN
5,3/31/2017,BT-A.L,United Kingdom,BT Group,24062000.0,5336000.0,18726000.0,14611000.0,4115000.0,-807000.0,...,-945000.0,-945000.0,7691000.0,0.0,-1.776600e+05,NaN,1908000.0,3572000.0,692000.0,NaN
2,12/31/2019,600525.ss,China,Changyuan Group,6415002.0,3807464.0,2607538.0,2046328.0,213929.0,-365324.0,...,-582865.0,-582865.0,278765.0,0.0,-1.457160e+05,NaN,NaN,NaN,NaN,NaN
3,12/31/2018,600525.ss,China,Changyuan Group,7136879.0,4202858.0,2934021.0,2365128.0,88819.0,-517383.0,...,-1293980.0,-1293980.0,2367634.0,0.0,-3.234950e+05,NaN,NaN,NaN,NaN,NaN
4,12/31/2017,600525.ss,China,Changyuan Group,7432956.0,4074636.0,3358320.0,2080361.0,983659.0,-308375.0,...,-205864.0,-205864.0,1936217.0,0.0,-5.146600e+04,NaN,NaN,NaN,NaN,NaN
2,12/31/2019,CHL,Hong Kong,China Mobile,745917000.0,248375000.0,497542000.0,375550000.0,121992000.0,6819000.0,...,-8843000.0,-8843000.0,337033000.0,0.0,-2.201907e+06,13322000.0,106050000.0,182818000.0,NaN,NaN

Exports to Excel

In [20]:
import pandas
from openpyxl import load_workbook

book = load_workbook('Yahoo-Finance-Scrape-2020-09-23.xlsx')
writer = pandas.ExcelWriter('Yahoo-Finance-Scrape-2020-09-23.xlsx', engine='openpyxl')
writer.book = book
writer.sheets = {ws.title: ws for ws in book.worksheets}

for sheetname in writer.sheets:
    data.to_excel(writer,sheet_name=sheetname, startrow=writer.sheets[sheetname].max_row, index = False,header= True, na_rep='NA')

writer.save()